### ISSUE TITLE
Unexpected error from config file settings

### ISSUE THREAD

**Issue by engn33r** [rainshowerLabs/blutgang#18]
**Describe the bug**

When `health_check = false` is set in config.toml, the `health_check_ttl` value is still required.

**To Reproduce**
1. Download repo
2. Copy example_config.toml to config.toml
3. Set `health_check = false` and remove the line with `health_check_ttl`
4. Run `blutgang` and see error

**Expected behavior**
 No error

**Specs:**
 - OS: Ubuntu 22.04
 - Blutgang version: 0.1.0

**Blutgang options:**
N/A, just config file

**Comment by makemake-kbo** [comment]
fixed in https://github.com/rainshowerLabs/blutgang/commit/ac509e8c5cec1c537a3e33d264bdfde72d208f92
