### ISSUE TITLE
Unclear status messages

### ISSUE THREAD

**Issue by engn33r** [rainshowerLabs/blutgang#19]
**Describe the bug**
Possible nitpicks (except for "reorg detected" observation), but the verbose output messages should be consistent for actions that are in progress and require time to process vs. status messages.

**To Reproduce**
1. Run blutgang with default config and observe this output
![image](https://github.com/rainshowerLabs/blutgang/assets/6261182/13eeca27-be09-4cfc-9412-158172334ee2)

**Expected behavior**
1. The first line `Using config file at config.toml...` ends with `...` which makes it appear as though something is happening in the background. Most likely this is a status message. Consider removing `...`
2. The "Reorg detected" message appears every time that I run blutgang, even when I quickly kill blutgang and run it again so that the block number has not changed. Are the stale entries actually removed from the cache? This message indicates likely no
3. `Removing stale entries from the cache...` does not have an `OK!` after the `...`, which makes it unclear if this step has finished or is still in progress. Ideally a progress indicator could be shown for any step that may take non-trivial time with `OK!` appearing instead of the progress indicator when the step is complete.

**Comment by makemake-kbo** [comment]
The "Reorg detected" messages appear because the current head/finalized blocks get updated on startup. They are not stored on disk which is why you'll see these messages appear.

I have made the output more clear in https://github.com/rainshowerLabs/blutgang/commit/28e3ea6b39732ddb1dfa6253f66f3b7b843f1cb2

I am also open to the idea of color coding output for potentially easier readability

**Comment by engn33r** [comment]
I can confirm the output suggestions have been implemented where applicable. If "Reorg detected" always appears at startup, I may suggest not showing this message during the initial update process but only showing it after the updating is complete and data is streaming. If you think it's reasonable to always show the "Reorg detected" message on startup, you can close this issue - I may be overlooking an edge case where this message is useful.
