### ISSUE TITLE
[BUG] Error with one RPC

### ISSUE THREAD

**Issue by engn33r** [rainshowerLabs/blutgang#21]
**Describe the bug**

Blutgang with multiple RPCs encountered an error and cached this error, meaning I cannot run sothis unless I clear the blutgang cache.

**To Reproduce**
1. Add 4 RPCs into the config, then run blutgang with 'blutgang'
2. Run sothis with `sothis --mode fast_track --source_rpc http://127.0.0.1:3000 --contract_address 0xbebc44782c7db0a1a60cb6fe97d0b483032ff1c7 --storage_slot 80084422859880547211683076133703299733277748156566366325829078699459944778999 --origin_block 16790000 --terminal_block 16810000 --query_interval 100 --filename tripool_usdc.json`
3. Observe error message in blutgang:
```
Info: Forwarding to: https://eth.llamarpc.com
Info: Request time: 1.776612253s
LA 1072738384.7
Info: Forwarding to: https://mainnet.infura.io/v3/XXX
Info: Forwarding to: https://mainnet.infura.io/v3/XXX
Info: Forwarding to: https://mainnet.infura.io/v3/XXX
Info: Forwarding to: https://mainnet.infura.io/v3/XXX
Info: Forwarding to: https://mainnet.infura.io/v3/XXX
Info: Checking RPC health... Info: Forwarding to: https://eth.llamarpc.com
Info: Request time: 1.621386758s
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 1 but the index is 1', /home/engn33r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blutgang-0.1.1/src/balancer/balancer.rs:290:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/engn33r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blutgang-0.1.1/src/health/check.rs:185:47
```
4. sothis stops running due to this error. When restarting sothis, it gives this error
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/engn33r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blutgang-0.1.1/src/balancer/balancer.rs:228:15
```

It is possible the issue is with one of the RPC endpoints, since restarting blutgang without clearing the cache allows sothis to collect a few more blocks of data, and when sothis errors again (now with the error `Error: RequestFailed("\"missing trie node 76f6d499f93c48793a8c638aa1a7144046758f6fb28995a51dff4e46297e2cd5 (path ) state 0x76f6d499f93c48793a8c638aa1a7144046758f6fb28995a51dff4e46297e2cd5 is not available\"")`), I can keep restarting sothis and it slowly makes more and more progress collecting data on every restart.

**Expected behavior**
No error

**Comment by makemake-kbo** [comment]
Should be fixed? https://github.com/rainshowerLabs/blutgang/commit/8aa428579b078e94a3d80e10ca173637de14b487

**Comment by engn33r** [comment]
Yes it's fixed, though sothis still runs into the error about the missing trie node. The error is an artifact of the RPC endpoint https://eth-rpc.gateway.pokt.network because I can remove that RPC from the blutgang config and then I don't encounter this issue. And when I use only the pokt RPC endpoint, the error is very easy to recreate. It might be a useful endpoint for testing error conditions and error handling.
