### ISSUE TITLE
`Invalid argument type` when using Blutgang with viem

### ISSUE THREAD

**Issue by gskril** [rainshowerLabs/blutgang#35]
**Describe the bug**
When using a local Blutgang endpoint as an [HTTP transport in viem](https://viem.sh/docs/clients/transports/http.html#http-transport), I get `TypeError: Invalid argument type in ToBigInt operation`.

**To Reproduce**

1. Run Blutgang locally with the default config
2. Create a simple script with viem and use the local Blutgang endpoint as the transport (tested with `getBlockNumber()` and `getBalance()`)
```typescript
import { createPublicClient, http } from 'viem'
import { mainnet } from 'viem/chains'

const client = createPublicClient({
  chain: mainnet,
  transport: http('http://127.0.0.1:3000/'),
})

const data = await client.getBlockNumber()
console.log(data)
```
3. See error

**Expected behavior**
The current block number is logged

**Specs:**
 - OS: macOS 13.6
 - Blutgang version: 0.2.0 Myrddin
 - Viem version: 1.18.9

**Blutgang options:**
Default config (llamarpc and ankr RPCs)

**Additional context**
The viem script runs as expected when using either the Llama or Ankr RPCs directly

**Comment by makemake-kbo** [comment]
Ive been trying to debug this and the only reason i could see viem might be throwing that error is because its returning the blocknumber as hex, but i cant imagine that being an issue.

Ill have to make an issue on the viem github to debug this further as im not a js/ts person.

**Comment by gskril** [comment]
I added a comment to the viem issue, but I found a weird behavior related to the `Content-Type: application/json` header on the Blutgang side which might be related.

A standard RPC endpoint returns an error if that header is missing:

```bash
curl -X POST -d '{                                    
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": [],
    "id": 0
}' https://eth.llamarpc.com

# {"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid Request","data":"Expected request with `Content-Type: application/json`"}}
```

Blutgang still returns a response which I guess technically is [against the spec](https://www.jsonrpc.org/specification#error_object).

```bash
 curl -X POST -d '{                                    
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": [],
    "id": 0
}' http://127.0.0.1:3000/

# {"jsonrpc":"2.0","id":0,"result":"0x11b44c8"}
```

**Comment by makemake-kbo** [comment]
Nice catch! Ill add functionality to reject such requests.

**Comment by makemake-kbo** [comment]
Added: https://github.com/rainshowerLabs/blutgang/commit/0422b9cb4a1e8f5a57f0ef58b892c87b4c78cb45
