### ISSUE TITLE
Docker container compiled at runtime

### ISSUE THREAD

**Issue by vdoflip** [rainshowerLabs/blutgang#56]
**Describe the bug**
The binaries of the docker image are compiled at runtime in the CMD line of the Dockerfile.
This works for development purposes, but goes against docker best practices and makes deployment to k8s or production not ideal.

**To Reproduce**
Just deploy the docker image to compose / k8s

**Expected behavior**
The image runs instantly, with the prebuilt rust binaries. Ideally, the image should be built with a [multi-stage](https://docs.docker.com/build/building/multi-stage/) Dockerfile 

**Additional context**

**Comment by makemake-kbo** [comment]
Currently theres a `blutgang`(built from source) and `blutgang-prebuilt`(compiled) docker image. This definitely causes confusion, and using the wrong one wastes time and resources, especially if its being deployed as a part of a k8s cluster.

Im in favour of deprecating `blutgang-prebuilt` in favor of making the `blutgang` image be precompiled and ready to use immediately.

**Comment by makemake-kbo** [comment]
done https://github.com/rainshowerLabs/blutgang/releases/tag/0.3.0-rc1
