### ISSUE TITLE
[Low Priority] log message spelling

### ISSUE THREAD

**Issue by 0xjimmy** [rainshowerLabs/blutgang#86]
https://github.com/rainshowerLabs/blutgang/blob/f3e42b3e089d38d2e6fa893f2b92326a53739429/src/health/check.rs#L242

**Comment by makemake-kbo** [comment]
fixed in https://github.com/rainshowerLabs/blutgang/commit/8cac8a42dc929d345679ccfeb92a96f3e91c70ea
