### ISSUE TITLE
How to clear the cache?

### ISSUE THREAD

**Issue by engn33r** [rainshowerLabs/blutgang#9]
**Is your feature request related to a problem? Please describe.**

If I'm testing the speed of blutgang and want to clear the cache, is there a CLI arg to do so?

**Describe the solution you'd like**

A CLI arg to clear the cache. Another option is documenting a manual process in the README.

**Describe alternatives you've considered**

Documenting a manual process.

**Additional context**

N/A

**Comment by makemake-kbo** [comment]
`do_clear = true ` in the config or `--clear` should do the trick. proper docs will be a thing soon-ish
